### ISSUE TITLE
Feature Request: Camera as input.

### ISSUE THREAD

**Issue by timoc** [billthefarmer/scope#10]
I'm interested in knowing the light spectra for a given light source. I want to use this to see how suited to sleep a given environment is (see [this research](http://www.livescience.com/53874-blue-light-sleep.html)).  

My request therefore is to add the camera as a source for your frequency Spectrum Analyzer. This would involve converting the color information a source image into the corresponding light frequency (some baseline camera calibration may be required?). The spectrum UI also might need some way to show the light frequency to color relationship.

If this could work with video, then, it could be used to actively detect problematic light sources.

**Comment by billthefarmer** [comment]
All my audio apps are built around the android audio system. I did have a previous request for sensor input - there is a very good sensor input app on F-Droid. To do a light spectrum from the camera is a completely different app. Whether there is one - I don't know.

**Comment by timoc** [comment]
ok
