### ISSUE TITLE
update via f-droid fails 

### ISSUE THREAD

**Issue by diegorodriguezv** [billthefarmer/scope#11]
Hello.
Today I received a notification for an update on Oscilloscope. After downloading it, it fails with an error like:
Error installing Oscilloscope
Installation failed due to an unknown error
The wording may not be exact, my phone is in Spanish.
I have a Sony Xperia z2 with Android 6.0.1.
How can I help?

**Comment by diegorodriguezv** [comment]
I have Oscilloscope v1.11 and the update that fails is v1.12

**Comment by billthefarmer** [comment]
Yes that happens on android 6, but not on 4.4, or 5.1. It may be because I changed the target api version. The same thing happens with my tuner app. The solution is to uninstall it and install the latest version. You will lose the settings, but there are only two of them.
