### ISSUE TITLE
Scope Version 1.12

### ISSUE THREAD

**Issue by Jazcafe** [billthefarmer/scope#12]
Hi Bill,

Love the Oscilloscope.  Did you know that the v1.12 apk won't install.  It looks like the file is corrupt, on this site and on F-Droid?  Any chance of re-building it?

Thanks.

**Comment by billthefarmer** [comment]
You need to uninstall the old version, see #11.

**Comment by Jazcafe** [comment]
Thanks.  Sorry, I didn't look at closed issues.
