### ISSUE TITLE
Max hold/waterfall

### ISSUE THREAD

**Issue by x8-999-github** [billthefarmer/scope#18]
Helllo,

I like your nice looking app. For the spectrum view it would be nice to have a waterfall or a visual max hold/delay with lots of cool colors!

**Comment by billthefarmer** [comment]
The spectrum display is an implementation of a [spectrum analyser](https://en.wikipedia.org/wiki/Spectrum_analyzer). If you want a colourful display, there are plenty of apps out there that can do that.

**Comment by x8-999-github** [comment]
It looks like your target for a spectrum analyzer is more bare bones. I enjoy using your app but it would be more useful to me if there was some kind of hold for the max values. If this is not the direction you want to go that is fine.

I quite like 
https://blog.yavilevich.com/2016/08/why-use-fosphor-a-gnu-radio-real-time-spectrum-analyzer/

**Comment by billthefarmer** [comment]
I have published a new release with a spectrum hold feature.

**Comment by x8-999-github** [comment]
I was able to install it using f-droid nice!
