### ISSUE TITLE
Last key (settings) not visible on small phone displays 

### ISSUE THREAD

**Issue by HoWilgh** [billthefarmer/scope#2]
Hallo,  
I saw on the screenshots that there should be an additional settings key. On my screen is the "Start" key the last one I see and I therefore can't switch to spectrum view. 
Thank for this nice app.

**Comment by billthefarmer** [comment]
I have made some changes that make the last four items on the action bar conditional, so they appear in the menu if not visible. It appears to work, so that should fix it. I will release a new version when I have tested it properly so it will appear on F-Droid.
