### ISSUE TITLE
View ultrasonic frequencies

### ISSUE THREAD

**Issue by RenaKunisaki** [billthefarmer/scope#20]
Many devices' mics are able to pick up sounds outside the human hearing range. Is there any way to show outside this range?

**Comment by billthefarmer** [comment]
There is no interface provided by Android, as on other platforms, to discover the capabilities of the audio input hardware. Therefore I use [getNativeOutputSampleRate()](https://developer.android.com/reference/android/media/AudioTrack.html#getNativeOutputSampleRate(int)) and use it on the input. This has always been 44100 samples per second, on the devices I have tested, which limits the highest frequency to half that, about 22KHz.

Bearing in mind that the microphone on a phone is designed for speech and noise cancelling, I don't think you are going to get much high frequency performance.
