### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [billthefarmer/scope#21]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by billthefarmer** [comment]
See [18](https://github.com/billthefarmer/sig-gen/issues/18).

**Comment by c-e-p-x-u-o** [comment]
Scope runs only on android. Please reopen.

**Comment by billthefarmer** [comment]
[Mac, WIndows version](https://github.com/billthefarmer/audiotools/releases/tag/v1.02)
