### ISSUE TITLE
Extension of input source to light and magnetic field 

### ISSUE THREAD

**Issue by root-ruud** [billthefarmer/scope#24]
I use Bill's oscilloscope and function generator for my job. This post is about the oscilloscope. I noticed that there are currently four options for input source: all audio. For me it would be extremely useful if this could be extended to the magnetic sensors on my smartphone. It would be great to see the magnetic field (x,y,z) in time and especially the spectrum!
To a lesser extent, it may be nice to also have the light meter of the camera as an input source. We could then measure the frequency of LED-lights and the like, and also rotation speeds of wheels.

**Comment by billthefarmer** [comment]
See #3 and #10. There is an app on F-Droid that does this, Sensor Readout. This app is an audio app, it would require a major redesign to change it.

**Comment by root-ruud** [comment]
Thanks for you reply, Bill. I have tested Sensor Readout and it lacks a spectrum. Also your oscilloscope looks a lot nicer and had superior controls. How much work would it be to adapt your oscilloscope? I may be able to help financially, I have a limited budget for this.
