### ISSUE TITLE
Audio jack

### ISSUE THREAD

**Issue by alexandre-mbm** [billthefarmer/scope#26]
See [this instructable](https://www.instructables.com/id/Use-Your-Laptop-as-Oscilloscope/) please.

![Audio jack schematic](https://cdn.instructables.com/F44/1A1E/HH2VN4DO/F441A1EHH2VN4DO.LARGE.jpg)

Does it support?

**Comment by billthefarmer** [comment]
I investigated this intending to write a [TDR](https://github.com/billthefarmer/tdr) ([Time Domain Reflectometer](https://en.wikipedia.org/wiki/Time-domain_reflectometer)). However some idiot decided at some point that, on phones, the microphone input is on the outer sheath of the jack. Look it up. So, providing you can make up a suitable jack it should work. However I do have an Oscilloscope app as part of my [AudioTools](https://github.com/billthefarmer/audiotools). There are Windows, MacOS, and Linux versions and it is free open source software.
