### ISSUE TITLE
Play Store release?

### ISSUE THREAD

**Issue by MrHeating** [billthefarmer/scope#28]
Any chance for us to have the app on the play store? I know I can install it from GitHub/F-Droid, but that option doesn't appeal to less tech literate folk who would rather just install some suggested app than go to the settings once.

**Comment by billthefarmer** [comment]
Publishing apps on the play store requires signing up to their commercial in-your-face ethos and complying with continually shifting requirements. It also costs money. My apps are designed to do one thing reasonably well, and be free and open source.
