### ISSUE TITLE
Switch for input audio/sensors 

### ISSUE THREAD

**Issue by HoWilgh** [billthefarmer/scope#3]
Hi, 
It would be extremely useful to have a switch for selecting the input. 
Ingesting inputs would be:
-Internal mic 
-Headset mic (plug)
-Bluetooth audio in 
-Various sensors like accelerometer x,y,z
Thanks in advance

**Comment by billthefarmer** [comment]
I have added selection for audio sources. There isn't one for the headset mic, I assume the mic input gets switched when you plug the headset in. Using sensor inputs would require a major redesign as the sensor input is event driven, rather than a stream.

**Comment by HoWilgh** [comment]
Hi bill, 

Thank you for adopting the app.

Maybe the following projects could help to realize the "event driving" for the sensors input 

https://f-droid.org/repository/browse/?fdfilter=Seismo&fdid=com.ariwilson.seismowallpaper

The sources can be found here :
https://github.com/evilrobot69/code/tree/master/SeismoWallpaper
And for a similar app... 
https://github.com/evilrobot69/code/tree/master/Seismo

Br

**Comment by root-ruud** [comment]
If someone wants to make this extension to the app, I am very enthousiastic. Especially a spectrum of the magnetometers is useful for me. I may be able to help achieve this. I am not a coder, but I have a limited budget to facilitate this.

**Comment by billthefarmer** [comment]
I looked at this at the time. I don't think you can get data from sensors fast enough or consistently enough to make a spectrum meaningful. See [Android accelerometer: Sampling Rate?](https://stackoverflow.com/questions/17663191/android-accelerometer-sampling-rate). Useful data on the magnetic sensor is exceedingly sparse.
