### ISSUE TITLE
Rising Edge vs Falling Edge Trigger Setting

### ISSUE THREAD

**Issue by RageGamerBoi** [billthefarmer/scope#35]
Please add a button to switch the trigger (sync level) between triggering on the rising edge or on the falling edge of a wave.

**Comment by RageGamerBoi** [comment]
Ah, no I'm talking about this:

https://www.picotech.com/library/oscilloscopes/advanced-digital-triggers (don't worry about the advanced trigger modes, it's useless to most people)

it's a little nit-picky because everything else is good enough already, but it's common enough that I think I should mention it, and it makes the wave sync to the start of the screen much better (give the video on that website a watch to see what I mean).

Oh, and that was just the first result on Google, I don't even know who "PicoScope" is.

Thanks :)

**Comment by billthefarmer** [comment]
The sync already works like that. It calculates the rate of change and triggers when the value is going in the right direction and passes the threshold, defined by the pointer in the Y scale.

**Comment by RageGamerBoi** [comment]
Ah, alright.
