### ISSUE TITLE
Feature Request THD (Total Harmonic Distortion)

### ISSUE THREAD

**Issue by pwrsource** [billthefarmer/scope#39]
Hi Team,

I think it would be really fantastic to have an option to calculate the THD of the signal (via FFT).
No other app seems to have this feature, but its common on physical units.
Here is some arduino-based code: 
https://picocosm.wordpress.com/2022/04/10/15-scoping-out-your-voltage/
https://github.com/picosapiens/ranocchio

Cheers!

**Comment by billthefarmer** [comment]
I have tested this, I get about 3% for a sine wave from my [SigGen](https://github.com/billthefarmer/sig-gen) app, about 40% for a square wave via the phone speaker/microphone. The calculation is...
```java

                // Sum of harmonics
                double sumh = 0.0;
                // Sum of fundamental
                double sumf = 0.0;
                for (int i = 1; i < RANGE; i++)
                    // Sum the fundamental
                    if (Math.abs(xf[i] - frequency) < fps)
                        sumf += xa[i] * xa[i];

                    // Sum the harmonics
                    else if (Math.IEEEremainder(xf[i], frequency) <
                             Math.round(xf[i] / frequency) * fps)
                        sumh += xa[i] * xa[i];

                // Total harmonic distortion
                double thd = Math.sqrt(sumh / sumf) * 100.0;
```
Where `xa[]` is the fft amplitude, `xf[]` is the calculated actual frequency and `fps` is frequency per fft slot.

**Comment by pwrsource** [comment]
This looks correct to me, according to my knowledge of thd (and link here)
https://www.allaboutcircuits.com/technical-articles/the-importance-of-total-harmonic-distortion/

Well done!
Could we do some benchmark tests against ARTA software? 
Thanks for including the note on the square wave, seems fairly good.  I'm thinking we might be able to improve the accuracy by making the bin size adjustable in the app.
Thoughts?

**Comment by billthefarmer** [comment]
The app is primarily a scope/spectrum, adding THD is a bolt-on extra. The FFT is only 4K, which is why the frequency is only shown to one decimal. Tweaking it to make the THD more accurate is outside the scope, that's another app.

**Comment by pwrsource** [comment]
All good! No problem, well done on integrating THD into the app.
Looking forward to using this! :D
