### ISSUE TITLE
Scale on the your axis

### ISSUE THREAD

**Issue by HoWilgh** [billthefarmer/scope#4]
Hallo, 
Also unit e.G. Volt on/for the y axis would be helpful. 
Thanks

**Comment by billthefarmer** [comment]
The device audio input must include [AGC](https://en.wikipedia.org/wiki/Automatic_gain_control) to prevent the [A to D](https://en.wikipedia.org/wiki/Analog-to-digital_converter) from being overloaded. Also the scope display has [AGC](https://en.wikipedia.org/wiki/Automatic_gain_control) built in with a maximum gain of 8. That prevents the noise within the device filling the display.

Therefore there is no point in having an input gain control or scaling on the Y axis, as it would be meaningless.
