### ISSUE TITLE
Trigger

### ISSUE THREAD

**Issue by morfeus2** [billthefarmer/scope#6]
Nice app!
I have a feature request:
could you add the possibility to select the trigger level? Some sliding line like the horizontal one (but of course vertical) would be perfect. (in this way you could remove the button for polarity and leave more space for other buttons).

Regards,
Luca

**Comment by billthefarmer** [comment]
I have added a sync level control in the left edge Y scale. It should appear on F-Droid within the next day or so. It won't appear until you touch the scale.

**Comment by morfeus2** [comment]
Wow, I am really impressed for the super fast implementation!
Thanks!
