### ISSUE TITLE
Feature Request: Keep screen on

### ISSUE THREAD

**Issue by Nold360** [billthefarmer/scope#7]
Hi,

I really like your app but I'm missing a feature to keep the screen on.
ATM I have to set the screen-timeout manually in the OS-Settings, so a simple switch in the settings of your app would be really nice!

Thanks a lot & kind Regards, Nold.

**Comment by billthefarmer** [comment]
I have released a new version with a screen option in the preferences. It should be on F-Droid within a day or so.
