### ISSUE TITLE
Can you set the flag to allow it to be installed on an external microSD card?

### ISSUE THREAD

**Issue by Gitoffthelawn** [billthefarmer/scope#8]
This excellent app is still small (yea!), but can you set the flag to allow it to be installed on an external memory card?

**Comment by billthefarmer** [comment]
I have set the install location to auto which should allow it to be installed in either and moved from one to the other according to the docs. I haven't got a device with external storage to test it.

**Comment by Gitoffthelawn** [comment]
Thanks!  :-)

**Comment by Gitoffthelawn** [comment]
Tested.  It works.  Thanks!
