### ISSUE TITLE
Actually No issue ..... Want to learn

### ISSUE THREAD

**Issue by ALI-rizvi01** [billthefarmer/scope#9]
you make source code open which is great help for those who want to learn how to make android apps.....
But i want to know how this app make  .... mean how oscilocope work is completely different in normally .... then appp so ..... you have any tutorial or some resourses to learn this code .....

**Comment by billthefarmer** [comment]
This app uses a state machine to process the audio input in a background thread. It is a port of the same app that I wrote for windows and OSX, also on github called audio tools.
Hope this helps.
Regards Bill

**Comment by ALI-rizvi01** [comment]
yh may be .... but how we know what activites state machine have to done in background to be look like osciloscope ..... (i may be litlle bit annoying for you and i already sorry for that but actually i want to know) .......  what things should be considered …. (if you can refer any resourses, links, videos or something i will be very thank full)

**Comment by ALI-rizvi01** [comment]
I think My question was awkward .......... your app is Nice ......  can You Update Your App to work with Buletooth .... with no wired connections ....

**Comment by moriel5** [comment]
As someone who is looking to step his toes into working with oscilloscopes, is this only for audio, or could I, theoretically, use it to test things like voltage ripple of electricity going through the USB port while the device is charging (not directly testing the charger, just what happens in between the port and the rest of the system)?

**Comment by billthefarmer** [comment]
The app is dependent on the audio hardware in the device it's running on. Apart from that it could be used to measure anything that you can make an adapter for. See #26.
